/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dvd.management.system;

import DataAccessObject.Logdao;
import DataAccessObject.Userdao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.ListSelectionModel;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.DefaultTableModel;
import model.Log;
import model.User;

/**
 *
 * @author ASUS-NOTEBOOK
 */
public class adminHome extends javax.swing.JFrame {
    int dbid;
    public String d = "C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\icon\\";
    /**
     * Creates new form adminHome
     */
    public adminHome() {
        initComponents();
    }
    
    public adminHome(int id) {
        initComponents();
        
        jTable1.getTableHeader().setFont(new Font("Retro Gaming", Font.BOLD, 12));
        jTable1.getTableHeader().setForeground(new Color(0,0,0));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.setShowGrid(false);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setBackground(new Color(0,0,0));
        jTable1.setOpaque(false);
        jScrollPane1.getColumnHeader().setVisible(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBackground(Color.BLACK);
        jScrollPane1.getVerticalScrollBar().setBackground(Color.BLACK);
        jScrollPane1.getVerticalScrollBar().setUI(new BasicScrollBarUI(){
             @Override
             protected void configureScrollBarColors() {
                 
                 
            this.thumbColor = Color.cyan;
            }
             
            @Override
             protected JButton createDecreaseButton(int orientation) {
                return createZeroButton();
            }
            @Override    
            protected JButton createIncreaseButton(int orientation) {
                return createZeroButton();
            }
            private JButton createZeroButton() {
            JButton jbutton = new JButton();
            jbutton.setPreferredSize(new Dimension(0, 0));
            jbutton.setMinimumSize(new Dimension(0, 0));
            jbutton.setMaximumSize(new Dimension(0, 0));
            return jbutton;
        }

        });
        
        jTable2.getTableHeader().setFont(new Font("Retro Gaming", Font.BOLD, 12));
        jTable2.getTableHeader().setForeground(new Color(0,0,0));
        jTable2.getTableHeader().setOpaque(false);
        jTable2.setShowGrid(false);
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable2.getTableHeader().setBackground(new Color(0,0,0));
        jTable2.setOpaque(false);
        jScrollPane2.getColumnHeader().setVisible(false);
        jScrollPane2.setBorder(null);
        jScrollPane2.getViewport().setBackground(Color.BLACK);
        jScrollPane2.getVerticalScrollBar().setBackground(Color.BLACK);
        jScrollPane2.getVerticalScrollBar().setUI(new BasicScrollBarUI(){
             @Override
             protected void configureScrollBarColors() {
                 
                 
            this.thumbColor = Color.cyan;
            }
             
            @Override
             protected JButton createDecreaseButton(int orientation) {
                return createZeroButton();
            }
            @Override    
            protected JButton createIncreaseButton(int orientation) {
                return createZeroButton();
            }
            private JButton createZeroButton() {
            JButton jbutton = new JButton();
            jbutton.setPreferredSize(new Dimension(0, 0));
            jbutton.setMinimumSize(new Dimension(0, 0));
            jbutton.setMaximumSize(new Dimension(0, 0));
            return jbutton;
        }

        });
        
        dbid = id;
        User user = null;
        user = Userdao.getAll(id);
        txtName.setBackground(new java.awt.Color(0,0,1));
        txtEmail.setBackground(new java.awt.Color(0,0,1));
        
        txtName.setText(user.getName());
        txtEmail.setText(user.getEmail());
        
        
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnlogout = new javax.swing.JToggleButton();
        btnEditFilm = new javax.swing.JToggleButton();
        btnGenre = new javax.swing.JToggleButton();
        btnAddfilm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnsmtp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnCname = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnCpassword = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogout.setBackground(new java.awt.Color(0, 0, 0));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imguser/logout.gif"))); // NOI18N
        btnlogout.setBorder(null);
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnlogoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnlogoutMouseReleased(evt);
            }
        });
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        btnEditFilm.setBackground(new java.awt.Color(0, 0, 0));
        btnEditFilm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminimg/EDITFILMS.png"))); // NOI18N
        btnEditFilm.setBorder(null);
        btnEditFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditFilmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditFilmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditFilmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditFilmMouseReleased(evt);
            }
        });
        btnEditFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFilmActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        btnGenre.setBackground(new java.awt.Color(0, 0, 0));
        btnGenre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ManageGenres/MANAGE GENRES.png"))); // NOI18N
        btnGenre.setBorder(null);
        btnGenre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenreMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGenreMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnGenreMouseReleased(evt);
            }
        });
        btnGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenreActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        btnAddfilm.setBackground(new java.awt.Color(0, 0, 0));
        btnAddfilm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminimg/addfilm1.png"))); // NOI18N
        btnAddfilm.setBorder(null);
        btnAddfilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddfilmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddfilmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddfilmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddfilmMouseReleased(evt);
            }
        });
        btnAddfilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddfilmActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddfilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Admin Login History"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(137, 92, 183));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 210, 130));

        btnsmtp.setBackground(new java.awt.Color(0, 0, 0));
        btnsmtp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminimg/modifysmtps1.png"))); // NOI18N
        btnsmtp.setBorder(null);
        btnsmtp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsmtpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsmtpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnsmtpMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnsmtpMouseReleased(evt);
            }
        });
        btnsmtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsmtpActionPerformed(evt);
            }
        });
        jPanel1.add(btnsmtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jTable2.setBackground(new java.awt.Color(0, 0, 0));
        jTable2.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Log ID", "Name", "Date & Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setFocusable(false);
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(137, 92, 183));
        jTable2.getTableHeader().setResizingAllowed(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 530, 130));

        btnCname.setBackground(new java.awt.Color(0, 0, 0));
        btnCname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminimg/change name.png"))); // NOI18N
        btnCname.setBorder(null);
        btnCname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCnameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCnameMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCnameMouseReleased(evt);
            }
        });
        btnCname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCnameActionPerformed(evt);
            }
        });
        jPanel1.add(btnCname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        txtEmail.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 156, 70, 10));

        txtName.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, -1));

        btnCpassword.setBackground(new java.awt.Color(0, 0, 0));
        btnCpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminimg/change password.png"))); // NOI18N
        btnCpassword.setBorder(null);
        btnCpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCpasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCpasswordMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCpasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCpasswordMouseReleased(evt);
            }
        });
        btnCpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(btnCpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Modifyusers/MODIFY USERS.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dvd/management/system/pogingadming (2).gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminimg/admin.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
         setVisible(false);
       new Loginback().setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnEditFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFilmActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ViewEditDelete ep;
        ep = new ViewEditDelete(dbid);
        ep.setVisible(true);

       
    }//GEN-LAST:event_btnEditFilmActionPerformed

    private void btnGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenreActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ManageGenre ep;
        ep = new ManageGenre(dbid);
        ep.setVisible(true);

    }//GEN-LAST:event_btnGenreActionPerformed

    private void btnAddfilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddfilmActionPerformed
        // TODO add your handling code here:
      setVisible(false);
      AddFilm ep;
      ep = new AddFilm(dbid);
      ep.setVisible(true);

    }//GEN-LAST:event_btnAddfilmActionPerformed

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        
            
        
    }//GEN-LAST:event_jTable1ComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Log> list = Logdao.getLogRecords(dbid);
        Iterator<Log> itr = list.iterator();
        while(itr.hasNext()){
            Log logObj = itr.next();
            dtm.addRow(new Object[]{logObj.getLogindate()});
        }
        
        DefaultTableModel dtmm = (DefaultTableModel) jTable2.getModel();
        ArrayList<User> listtt = Userdao.getAllRecords();
        ArrayList<Log> listt = Logdao.getAllLogRecords();
        Iterator<Log> itrr = listt.iterator();
        Iterator<User> itrrr = listtt.iterator();
        while(itrr.hasNext()  ){     
            Log logObj = itrr.next();
            dtmm.addRow(new Object[]{logObj.getLogId(),logObj.getName(),logObj.getLogindate()});
            /*while(itrrr.hasNext()){
                User userObj = itrrr.next();
                dtmm.addRow(new Object[]{logObj.getLogId(),userObj.getName(),logObj.getLogindate()});
            }*/
            
        }
    }//GEN-LAST:event_formComponentShown

    private void btnsmtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsmtpActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        modifysmtp ep;
        ep = new modifysmtp(dbid);
        ep.setVisible(true);
    }//GEN-LAST:event_btnsmtpActionPerformed

    private void btnCnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCnameActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ChangeName cn;
        cn = new ChangeName(dbid);
        cn.setVisible(true);
    }//GEN-LAST:event_btnCnameActionPerformed

    private void btnCpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCpasswordActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ChangePassword cn;
        cn = new ChangePassword(dbid);
        cn.setVisible(true);
    }//GEN-LAST:event_btnCpasswordActionPerformed

    private void btnEditFilmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditFilmMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Editfilms\\";
        String i ="EDITFILMSanimated.gif";
        icon = new ImageIcon(d+i2+i);
        btnEditFilm.setIcon(icon);
    }//GEN-LAST:event_btnEditFilmMouseEntered

    private void btnEditFilmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditFilmMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Editfilms\\";
        String i ="EDITFILMS.png";
        icon = new ImageIcon(d+i2+i);
        btnEditFilm.setIcon(icon);
    }//GEN-LAST:event_btnEditFilmMouseExited

    private void btnEditFilmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditFilmMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Editfilms\\";
        String i ="EDITFILMSclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnEditFilm.setIcon(icon);
    }//GEN-LAST:event_btnEditFilmMousePressed

    private void btnEditFilmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditFilmMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Editfilms\\";
        String i ="EDITFILMS.png";
        icon = new ImageIcon(d+i2+i);
        btnEditFilm.setIcon(icon);
    }//GEN-LAST:event_btnEditFilmMouseReleased

    private void btnGenreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenreMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="ManageGenres\\";
        String i ="MANAGE GENRESanimated.gif";
        icon = new ImageIcon(d+i2+i);
        btnGenre.setIcon(icon);
    }//GEN-LAST:event_btnGenreMouseEntered

    private void btnGenreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenreMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="ManageGenres\\";
        String i ="MANAGE GENRES.png";
        icon = new ImageIcon(d+i2+i);
        btnGenre.setIcon(icon);
    }//GEN-LAST:event_btnGenreMouseExited

    private void btnGenreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenreMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="ManageGenres\\";
        String i ="MANAGE GENRESclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnGenre.setIcon(icon);
    }//GEN-LAST:event_btnGenreMousePressed

    private void btnGenreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenreMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="ManageGenres\\";
        String i ="MANAGE GENRES.png";
        icon = new ImageIcon(d+i2+i);
        btnGenre.setIcon(icon);
    }//GEN-LAST:event_btnGenreMouseReleased

    private void btnAddfilmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddfilmMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Addfilm\\";
        String i ="addfilmanimated.gif";
        icon = new ImageIcon(d+i2+i);
        btnAddfilm.setIcon(icon);
    }//GEN-LAST:event_btnAddfilmMouseEntered

    private void btnAddfilmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddfilmMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Addfilm\\";
        String i ="addfilm1.png";
        icon = new ImageIcon(d+i2+i);
        btnAddfilm.setIcon(icon);
    }//GEN-LAST:event_btnAddfilmMouseExited

    private void btnAddfilmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddfilmMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Addfilm\\";
        String i ="addfilmclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnAddfilm.setIcon(icon);
    }//GEN-LAST:event_btnAddfilmMousePressed

    private void btnAddfilmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddfilmMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Addfilm\\";
        String i ="addfilm1.png";
        icon = new ImageIcon(d+i2+i);
        btnAddfilm.setIcon(icon);
    }//GEN-LAST:event_btnAddfilmMouseReleased

    private void btnsmtpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsmtpMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Modifysmtp\\";
        String i ="manage smtpanimated.gif";
        icon = new ImageIcon(d+i2+i);
        btnsmtp.setIcon(icon);
    }//GEN-LAST:event_btnsmtpMouseEntered

    private void btnsmtpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsmtpMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Modifysmtp\\";
        String i ="manage smtp.png";
        icon = new ImageIcon(d+i2+i);
        btnsmtp.setIcon(icon);
    }//GEN-LAST:event_btnsmtpMouseExited

    private void btnsmtpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsmtpMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Modifysmtp\\";
        String i ="manage smtpclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnsmtp.setIcon(icon);
    }//GEN-LAST:event_btnsmtpMousePressed

    private void btnsmtpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsmtpMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Modifysmtp\\";
        String i ="manage smtp.png";
        icon = new ImageIcon(d+i2+i);
        btnsmtp.setIcon(icon);
    }//GEN-LAST:event_btnsmtpMouseReleased

    private void btnCnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCnameMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Changename\\";
        String i ="change nameanimated.gif";
        icon = new ImageIcon(d+i2+i);
        btnCname.setIcon(icon);
    }//GEN-LAST:event_btnCnameMouseEntered

    private void btnCnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCnameMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Changename\\";
        String i ="change name.png";
        icon = new ImageIcon(d+i2+i);
        btnCname.setIcon(icon);
    }//GEN-LAST:event_btnCnameMouseExited

    private void btnCnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCnameMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Changename\\";
        String i ="change nameclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnCname.setIcon(icon);
    }//GEN-LAST:event_btnCnameMousePressed

    private void btnCnameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCnameMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Changename\\";
        String i ="change name.png";
        icon = new ImageIcon(d+i2+i);
        btnCname.setIcon(icon);
    }//GEN-LAST:event_btnCnameMouseReleased

    private void btnCpasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCpasswordMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Changepassword\\";
        String i ="change passwordanimated.gif";
        icon = new ImageIcon(d+i2+i);
        btnCpassword.setIcon(icon);
        
    }//GEN-LAST:event_btnCpasswordMouseEntered

    private void btnCpasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCpasswordMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Changepassword\\";
        String i ="change password.png";
        icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\adminimg\\change password.png");
        btnCpassword.setIcon(icon);
    }//GEN-LAST:event_btnCpasswordMouseExited

    private void btnCpasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCpasswordMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Changepassword\\";
        String i ="change passwordclick.png";
        icon = new ImageIcon(d+i2+i);
        btnCpassword.setIcon(icon);
    }//GEN-LAST:event_btnCpasswordMousePressed

    private void btnCpasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCpasswordMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        
        icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\adminimg\\change password.png");
        btnCpassword.setIcon(icon);
    }//GEN-LAST:event_btnCpasswordMouseReleased

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        // TODO add your handling code here:
         ImageIcon icon;
        String i2 ="Logout\\";
        String i ="logout.png";
        icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\imguser\\logout.gif");
        btnlogout.setIcon(icon);
    }//GEN-LAST:event_btnlogoutMouseExited

    private void btnlogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Logout\\";
        String i ="logout.png";
        icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\imguser\\logout.gif");
        btnlogout.setIcon(icon);
    }//GEN-LAST:event_btnlogoutMouseReleased

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Logout\\";
        String i ="logouthover.png";
        icon = new ImageIcon(d+i2+i);
        btnlogout.setIcon(icon);
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnlogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Logout\\";
        String i ="logoutclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnlogout.setIcon(icon);
    }//GEN-LAST:event_btnlogoutMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        modifyusers cn;
        cn = new modifyusers(dbid);
        cn.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Modifyusers\\";
        String i ="MODIFY USERSanimated.gif";
        icon = new ImageIcon(d+i2+i);
        jButton1.setIcon(icon);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Modifyusers\\";
        String i ="MODIFY USERS.png";
        icon = new ImageIcon(d+i2+i);
        jButton1.setIcon(icon);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Modifyusers\\";
        String i ="MODIFY USERS.png";
        icon = new ImageIcon(d+i2+i);
        jButton1.setIcon(icon);
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Modifyusers\\";
        String i ="MODIFY USERSclicked.png";
        icon = new ImageIcon(d+i2+i);
        jButton1.setIcon(icon);
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddfilm;
    private javax.swing.JButton btnCname;
    private javax.swing.JToggleButton btnCpassword;
    private javax.swing.JToggleButton btnEditFilm;
    private javax.swing.JToggleButton btnGenre;
    private javax.swing.JToggleButton btnlogout;
    private javax.swing.JButton btnsmtp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
