/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dvd.management.system;

import DataAccessObject.Mail;
import DataAccessObject.Userdao;
import DataAccessObject.otp;
import DataAccessObject.smtpdao;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Smtp;
import model.User;

/**
 *
 * @author ASUS-NOTEBOOK
 */
public class ChangeEmail extends javax.swing.JFrame {
    public String d = "C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\icon\\";
    public String SaveName;
    public int dbid;
    public String dbEmail;
    public String Email;
    public String dbToken;
    public String emailPattern = "^(.+)@(.+)$";
    
    
    /**
     * Creates new form ChangeEmail
     */
    public ChangeEmail() {
        initComponents();
    }
    
     public ChangeEmail(int id) {
        
        initComponents();
        txtEmail.setBackground(new java.awt.Color(0,0,1));
        txtNewEmail.setBackground(new java.awt.Color(0,0,1));
        txtOtp.setBackground(new java.awt.Color(0,0,1));
        
        User user = null;
        user = Userdao.getAll(id);
        dbid = id;
        dbEmail = user.getEmail();
        txtEmail.setText(user.getEmail());
        txtEmail.setEditable(false);
        txtOtp.setEditable(false);
        searchotp.setEnabled(false);
        btnSave.setEnabled(false);
        
    }
     
     public void validateFields(){
        String email = txtNewEmail.getText();
        
        if(email.matches(emailPattern) && !email.equals("")){
           searchotp.setEnabled(true); 
        } else{
           searchotp.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtNewEmail = new javax.swing.JTextField();
        txtOtp = new javax.swing.JTextField();
        searchotp = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 170, -1));

        txtNewEmail.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        txtNewEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtNewEmail.setBorder(null);
        txtNewEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewEmailActionPerformed(evt);
            }
        });
        txtNewEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewEmailKeyReleased(evt);
            }
        });
        jPanel1.add(txtNewEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 170, -1));

        txtOtp.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        txtOtp.setForeground(new java.awt.Color(255, 255, 255));
        txtOtp.setBorder(null);
        txtOtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOtpKeyReleased(evt);
            }
        });
        jPanel1.add(txtOtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 170, -1));

        searchotp.setBackground(new java.awt.Color(0, 0, 0));
        searchotp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgforogt/search.png"))); // NOI18N
        searchotp.setBorder(null);
        searchotp.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search/searchinactive.png"))); // NOI18N
        searchotp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchotpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchotpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchotpMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchotpMouseReleased(evt);
            }
        });
        searchotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchotpActionPerformed(evt);
            }
        });
        jPanel1.add(searchotp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgbutons/save.png"))); // NOI18N
        btnSave.setBorder(null);
        btnSave.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save/saveinactive.png"))); // NOI18N
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSaveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSaveMouseReleased(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgbutons/back.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackMouseReleased(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel3.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgbutons/new_email.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewEmailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        EditProfile ep;
        ep = new EditProfile(dbid);
        ep.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String token = txtOtp.getText();
        String newEmail = txtNewEmail.getText();
        String email = txtEmail.getText();
        if(token.equals(dbToken)){
            Userdao.updateEmail(email, newEmail);
            setVisible(false);
            EditProfile ep;
            ep = new EditProfile(dbid);
            ep.setVisible(true);
            
        }
        else{
            JOptionPane.showMessageDialog(null,"<html><b style =\"color:red\">Incorrect OTP</b></html>","Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void searchotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchotpActionPerformed
        // TODO add your handling code here:
        
        Email = txtNewEmail.getText();
        User user = new User();
        
        otp o = new otp();
        int l = 6; //max lenght of otp
        String token = String.valueOf(o.method(l));
        
        
        user.setToken(token);
        Userdao.updateToken(dbEmail,token);
        
       
        user = Userdao.getToken(dbEmail);
        if(user == null){
             int a = JOptionPane.showConfirmDialog(null,"<html><b style =\"color:red\">Incorrect E-mail</b></html>","Message", JOptionPane.ERROR_MESSAGE);
        }
        else {
            searchotp.setEnabled(false);
            txtNewEmail.setEditable(false);
            dbToken = user.getToken();
            txtEmail.setText(user.getEmail());
            validateFields();
            
            Smtp smtp = null;
            smtp = smtpdao.getSMTP();
            String email = smtp.getEmail();
            String password = smtp.getPassword();
            
            Mail mail = new Mail();
            mail.setupSeverProperties();
            try {

            mail.draftEmail(Email,token);
            mail.sendEmail(email,password);
    
            } catch (Exception ex){
                ex.printStackTrace();
            }
            searchotp.setEnabled(false);
            txtOtp.setEditable(true);
            JOptionPane.showMessageDialog(null,"OTP sent to your New Email","Message", JOptionPane.INFORMATION_MESSAGE);
            
            
        }
            
        
    }//GEN-LAST:event_searchotpActionPerformed

    private void txtNewEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewEmailKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtNewEmailKeyReleased

    private void txtOtpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOtpKeyReleased
        // TODO add your handling code here:
        
        
        String otp = txtOtp.getText();
        if(!otp.equals("")){
           btnSave.setEnabled(true);
        } else{
           btnSave.setEnabled(false);
        }
        
    }//GEN-LAST:event_txtOtpKeyReleased

    private void btnSaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Save\\";
        String i ="saveclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMousePressed

    private void btnSaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Save\\";
        String i ="save.png";
        icon = new ImageIcon(d+i2+i);
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMouseReleased

    private void searchotpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchotpMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Search\\";
        String i ="searchclicked.png";
        icon = new ImageIcon(d+i2+i);
        searchotp.setIcon(icon);
    }//GEN-LAST:event_searchotpMousePressed

    private void searchotpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchotpMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Search\\";
        String i ="searchhover.png";
        icon = new ImageIcon(d+i2+i);
        searchotp.setIcon(icon);
    }//GEN-LAST:event_searchotpMouseEntered

    private void searchotpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchotpMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Search\\";
        String i ="C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\imgver\\search.png";
        icon = new ImageIcon(i);
        searchotp.setIcon(icon);
    }//GEN-LAST:event_searchotpMouseExited

    private void searchotpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchotpMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Search\\";
        String i ="C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\imgver\\search.png";
        icon = new ImageIcon(i);
        searchotp.setIcon(icon);
    }//GEN-LAST:event_searchotpMouseReleased

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="back\\";
        String i ="back.png";
        icon = new ImageIcon(d+i2+i);
        btnBack.setIcon(icon);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="back\\";
        String i ="back.png";
        icon = new ImageIcon(d+i2+i);
        btnBack.setIcon(icon);
    }//GEN-LAST:event_btnBackMouseReleased

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="back\\";
        String i ="backhover.png";
        icon = new ImageIcon(d+i2+i);
        btnBack.setIcon(icon);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="back\\";
        String i ="backclick.png";
        icon = new ImageIcon(d+i2+i);
        btnBack.setIcon(icon);
    }//GEN-LAST:event_btnBackMousePressed

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Save\\";
        String i ="savehover.png";
        icon = new ImageIcon(d+i2+i);
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Save\\";
        String i ="save.png";
        icon = new ImageIcon(d+i2+i);
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeEmail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchotp;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNewEmail;
    private javax.swing.JTextField txtOtp;
    // End of variables declaration//GEN-END:variables
}
