/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dvd.management.system;

import DataAccessObject.Billdao;
import DataAccessObject.Userdao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.ListSelectionModel;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Bill;
import model.User;

/**
 *
 * @author ASUS-NOTEBOOK
 */
public class Home extends javax.swing.JFrame {
    public int dbid;
    public String d = "C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\icon\\";
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
    }
     public Home(int id) {
        initComponents();
        
        jTable1.getTableHeader().setFont(new Font("Retro Gaming", Font.BOLD, 12));
        jTable1.getTableHeader().setForeground(new Color(0,0,0));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.setShowGrid(false);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setBackground(new Color(0,0,0));
        jTable1.setOpaque(false);
        jScrollPane1.getColumnHeader().setVisible(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBackground(Color.BLACK);
        jScrollPane1.getVerticalScrollBar().setBackground(Color.BLACK);
        jScrollPane1.getVerticalScrollBar().setUI(new BasicScrollBarUI(){
             @Override
             protected void configureScrollBarColors() {
                 
                 
            this.thumbColor = Color.cyan;
            }
             
            @Override
             protected JButton createDecreaseButton(int orientation) {
                return createZeroButton();
            }
            @Override    
            protected JButton createIncreaseButton(int orientation) {
                return createZeroButton();
            }
            private JButton createZeroButton() {
            JButton jbutton = new JButton();
            jbutton.setPreferredSize(new Dimension(0, 0));
            jbutton.setMinimumSize(new Dimension(0, 0));
            jbutton.setMaximumSize(new Dimension(0, 0));
            return jbutton;
        }

        });
        
        dbid = id;
        User user = null;
        user = Userdao.getAll(id);
        txtName.setText(user.getName());
        txtEmail.setText(user.getEmail());
        
        jTable1.getTableHeader().setFont(new Font("Retro Gaming", Font.BOLD, 12));
        jTable1.getTableHeader().setForeground(new Color(255,255,255));
        
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(0,204,255));
       
        
   
    }
    
   
    

   
    
    /*public void scaleImage(){
        ImageIcon icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\images\\shrek.png");
        // img = icon.getImage();
        profilepic.setIcon(icon);
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JLabel();
        btnRent = new javax.swing.JButton();
        btnEditproile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnReturnFilm = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        txtName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setFont(new java.awt.Font("Retro Gaming", 1, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtEmail.setText("--");
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 280, -1));

        btnRent.setBackground(new java.awt.Color(0, 0, 0));
        btnRent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imguser/rentfilm.png"))); // NOI18N
        btnRent.setBorder(null);
        btnRent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRentMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRentMouseReleased(evt);
            }
        });
        btnRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentActionPerformed(evt);
            }
        });
        jPanel1.add(btnRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, 40));

        btnEditproile.setBackground(new java.awt.Color(0, 0, 0));
        btnEditproile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imguser/editprofile.png"))); // NOI18N
        btnEditproile.setBorder(null);
        btnEditproile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditproileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditproileMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditproileMousePressed(evt);
            }
        });
        btnEditproile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditproileActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditproile, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, -1, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Genre", "Title", "Total", "Rentdate", "Returndate", "Return Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(137, 92, 183));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(137, 92, 183));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 337, 840, 90));

        btnReturnFilm.setBackground(new java.awt.Color(0, 0, 0));
        btnReturnFilm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dvd/management/system/returnfilm1 (1).png"))); // NOI18N
        btnReturnFilm.setBorder(null);
        btnReturnFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReturnFilmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReturnFilmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReturnFilmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnReturnFilmMouseReleased(evt);
            }
        });
        btnReturnFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnFilmActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturnFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, -1));

        btnlogout.setBackground(new java.awt.Color(0, 0, 0));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imguser/logout.gif"))); // NOI18N
        btnlogout.setBorder(null);
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnlogoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnlogoutMouseReleased(evt);
            }
        });
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        txtName.setFont(new java.awt.Font("Retro Gaming", 1, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtName.setText("--");
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 340, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/email.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        usr.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        usr.setForeground(new java.awt.Color(204, 51, 0));
        usr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imguser/userhometab.gif"))); // NOI18N
        jPanel1.add(usr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
       setVisible(false);
       new Loginback().setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentActionPerformed
        // TODO add your handling code here:

       RentFilm1 rf;
       rf= new RentFilm1(dbid);
       rf.setVisible(true);
       setVisible(false);
       
    }//GEN-LAST:event_btnRentActionPerformed

    private void btnEditproileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditproileActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        EditProfile pro = new EditProfile();
        pro = new EditProfile (dbid);
        pro.setVisible(true);
    }//GEN-LAST:event_btnEditproileActionPerformed

    private void btnReturnFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnFilmActionPerformed
        // TODO add your handling code here:
        ReturnFilm rf;
        rf= new ReturnFilm(dbid);
        rf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnReturnFilmActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Bill> list = Billdao.getAllRecordsByUserId(dbid);   
        Iterator<Bill> itr = list.iterator();
        //ArrayList<User> lists = Userdao.getAllRecord(dbid);
       // Iterator<User> itrs = lists.iterator();
        while(itr.hasNext()){
            Bill billObj = itr.next();
            //User userObj = itrs.next();
            dtm.addRow(new Object[]{
                billObj.getId(), 
                billObj.getGenre(),
                billObj.getTitle(),
                billObj.getCost(),
                billObj.getRentdate(),
                billObj.getReturndate(),
                billObj.getReturnFilm()
                    
            });
            
        }
        
       
          
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
        int id = (int) model.getValueAt(index, 0);
        setVisible(false);
        new Reciept(id, dbid).setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEditproileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditproileMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Editprofile\\";
        String i ="editprofileanimated.gif";
        icon = new ImageIcon(d+i2+i);
        btnEditproile.setIcon(icon);
        
    }//GEN-LAST:event_btnEditproileMouseEntered

    private void btnEditproileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditproileMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Editprofile\\";
        String i ="editprofile.png";
        icon = new ImageIcon(d+i2+i);
        btnEditproile.setIcon(icon);
    }//GEN-LAST:event_btnEditproileMouseExited

    private void btnEditproileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditproileMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Editprofile\\";
        String i ="editprofileclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnEditproile.setIcon(icon);
    }//GEN-LAST:event_btnEditproileMousePressed

    private void btnRentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRentMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Rentfilm\\";
        String i ="rentfilmanimated.gif";
        icon = new ImageIcon(d+i2+i);
        btnRent.setIcon(icon);
    }//GEN-LAST:event_btnRentMouseEntered

    private void btnRentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRentMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Rentfilm\\";
        String i ="rentfilm.png";
        icon = new ImageIcon(d+i2+i);
        btnRent.setIcon(icon);
    }//GEN-LAST:event_btnRentMouseExited

    private void btnRentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRentMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Rentfilm\\";
        String i ="rentfilmclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnRent.setIcon(icon);
    }//GEN-LAST:event_btnRentMousePressed

    private void btnRentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRentMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Rentfilm\\";
        String i ="rentfilm.png";
        icon = new ImageIcon(d+i2+i);
        btnRent.setIcon(icon);
    }//GEN-LAST:event_btnRentMouseReleased

    private void btnReturnFilmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnFilmMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Returnfilm\\";
        String i ="returnfilmanimated.gif";
        icon = new ImageIcon(d+i2+i);
        btnReturnFilm.setIcon(icon);
    }//GEN-LAST:event_btnReturnFilmMouseEntered

    private void btnReturnFilmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnFilmMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Returnfilm\\";
        String i ="returnfilm.png";
        icon = new ImageIcon(d+i2+i);
        btnReturnFilm.setIcon(icon);
    }//GEN-LAST:event_btnReturnFilmMouseExited

    private void btnReturnFilmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnFilmMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Returnfilm\\";
        String i ="returnfilmclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnReturnFilm.setIcon(icon);
    }//GEN-LAST:event_btnReturnFilmMousePressed

    private void btnReturnFilmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnFilmMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Returnfilm\\";
        String i ="returnfilm.png";
        icon = new ImageIcon(d+i2+i);
        btnReturnFilm.setIcon(icon);
    }//GEN-LAST:event_btnReturnFilmMouseReleased

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Logout\\";
        String i ="logouthover.png";
        icon = new ImageIcon(d+i2+i);
        btnlogout.setIcon(icon);
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Logout\\";
        String i ="logout.png";
        icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\imguser\\logout.gif");
        btnlogout.setIcon(icon);
    }//GEN-LAST:event_btnlogoutMouseExited

    private void btnlogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMousePressed
        // TODO add your handling code here:
         ImageIcon icon;
        String i2 ="Logout\\";
        String i ="logoutclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnlogout.setIcon(icon);
    }//GEN-LAST:event_btnlogoutMousePressed

    private void btnlogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseReleased
        // TODO add your handling code here:
       ImageIcon icon;
        String i2 ="Logout\\";
        String i ="logout.png";
        icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\imguser\\logout.gif");
        btnlogout.setIcon(icon);
                                       
    }//GEN-LAST:event_btnlogoutMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditproile;
    private javax.swing.JButton btnRent;
    private javax.swing.JButton btnReturnFilm;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel usr;
    // End of variables declaration//GEN-END:variables

  
}
