/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dvd.management.system;

import DataAccessObject.Logdao;
import DataAccessObject.Userdao;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.Log;
import model.User;

/**
 *
 * @author ASUS-NOTEBOOK
 */
public class Loginback extends javax.swing.JFrame {
    public String emailPattern = "^(.+)@(.+)$";
    public String d = "C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\icon\\";
    public String s = "C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\DataAccessObject\\click.mp3";
    
    Clip clip;
     
    public Loginback() {
        
         try{
            for(UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()){
                if("Windows".equals(info.getName())){
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch (Exception ex){
            ex.getMessage();
        }
        
        initComponents();
        
        loginbutton.setEnabled(false);
        txtEmail.setBackground(new java.awt.Color(0,0,1));
        txtPassword.setBackground(new java.awt.Color(0,0,1));
    }
    
    public void setClick(){
        try{
            File sound = new File (s);
            clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(sound));
            clip.start();
        }catch(Exception e){
            
        }
    }
    
    
    public void clear(){
        txtEmail.setText("");
        txtPassword.setText("");
        loginbutton.setEnabled(false);
    }
    
    
    public void validateFields(){
        String email = txtEmail.getText();
        String password = txtPassword.getText();
        if(email.matches(emailPattern) && !password.equals("")){
           loginbutton.setEnabled(true); 
        } else{
            loginbutton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();
        btnVerify = new javax.swing.JButton();
        forgotpassbutton = new javax.swing.JButton();
        signupbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setFont(new java.awt.Font("Retro Gaming", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 170, 20));

        txtPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 170, 20));

        loginbutton.setBackground(new java.awt.Color(0, 0, 0));
        loginbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login.png"))); // NOI18N
        loginbutton.setBorder(null);
        loginbutton.setBorderPainted(false);
        loginbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginbutton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login/Loginnotactive.png"))); // NOI18N
        loginbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginbuttonMouseReleased(evt);
            }
        });
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 190, 50));

        btnVerify.setBackground(new java.awt.Color(0, 0, 0));
        btnVerify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Verify account.png"))); // NOI18N
        btnVerify.setBorderPainted(false);
        btnVerify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerifyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerifyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVerifyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVerifyMouseReleased(evt);
            }
        });
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 190, -1));

        forgotpassbutton.setBackground(new java.awt.Color(0, 0, 0));
        forgotpassbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Forgot password.png"))); // NOI18N
        forgotpassbutton.setBorderPainted(false);
        forgotpassbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpassbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotpassbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotpassbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                forgotpassbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                forgotpassbuttonMouseReleased(evt);
            }
        });
        forgotpassbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotpassbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(forgotpassbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 190, -1));

        signupbutton.setBackground(new java.awt.Color(0, 0, 0));
        signupbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Signup.png"))); // NOI18N
        signupbutton.setBorderPainted(false);
        signupbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signupbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signupbuttonMouseReleased(evt);
            }
        });
        signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(signupbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dvd/management/system/Login.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 374, 565));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        validateFields();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        validateFields();
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void loginbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Login\\";
        String i ="Loginanimated.gif";
        icon = new ImageIcon(d+i2+i);
        loginbutton.setIcon(icon);
        
    }//GEN-LAST:event_loginbuttonMouseEntered

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed

        String email = txtEmail.getText();
        String password = txtPassword.getText();
        User user = null;
        user = Userdao.login(email,password);
        if(user == null){
            JOptionPane.showMessageDialog(null,"<html><b style=\"color\">Incorrect E-mail or Passsword</b></html>","Message",JOptionPane.ERROR_MESSAGE);
        } else {
            if(user.getStatus().equals("Disabled")){
                JOptionPane.showMessageDialog(null,"<html><b style=\"color\">Your Account is not yet Verified</b></html>","Message",JOptionPane.INFORMATION_MESSAGE);
                clear();
            }

            if(user.getStatus().equals("Active")){
                setVisible(false);
                Log log = new Log();
                log.setUserId(user.getId());
                log.setName(user.getName());
                long mils = System.currentTimeMillis();
                java.util.Date sqldate = new java.util.Date(mils);
                DateFormat dateFormat = new SimpleDateFormat("MM-dd-yyyy hh:mm:ss");
                String date = dateFormat.format(sqldate);
                log.setLogindate(date);

                Logdao.saveLog(log);

                if(user.getType() == 2){
                    Home home;
                    home = new Home(user.getId());
                    home.setVisible(true);

                } else {
                    adminHome ahome;
                    ahome = new adminHome(user.getId());
                    ahome.setVisible(true);

                }

            }

        }
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new verifyaccount().setVisible(true);
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void forgotpassbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpassbuttonMouseEntered
        // TODO add your handling code here:
        
        ImageIcon icon;
        String i2 ="Editfilms\\";
        String i ="EDITFILMSanimated.gif";
        icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\images\\forgotpasswordani (3).gif");
        forgotpassbutton.setIcon(icon);

        
    }//GEN-LAST:event_forgotpassbuttonMouseEntered

    private void forgotpassbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpassbuttonMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Editfilms\\";
        String i ="EDITFILMSanimated.gif";
        icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\images\\Forgot password.png");
        forgotpassbutton.setIcon(icon);

        
    }//GEN-LAST:event_forgotpassbuttonMouseExited

    private void forgotpassbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotpassbuttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_forgotpassbuttonActionPerformed

    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed
        setVisible(false);
        new Register().setVisible(true);
    }//GEN-LAST:event_signupbuttonActionPerformed

    private void loginbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseClicked
        // TODO add your handling code here:
        
       
       
        
    }//GEN-LAST:event_loginbuttonMouseClicked

    private void loginbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Login\\";
        String i ="Loginclicked1.png";
        icon = new ImageIcon(d+i2+i);
        setClick();
        loginbutton.setIcon(icon);
        
        
    }//GEN-LAST:event_loginbuttonMousePressed

    private void loginbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Login\\";
        String i ="Login.png";
        icon = new ImageIcon(d+i2+i);
        loginbutton.setIcon(icon);
        
    }//GEN-LAST:event_loginbuttonMouseReleased

    private void loginbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Login\\";
        String i ="Login.png";
        icon = new ImageIcon(d+i2+i);
        loginbutton.setIcon(icon);
       
    }//GEN-LAST:event_loginbuttonMouseExited

    private void btnVerifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnVerifyMouseClicked

    private void btnVerifyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="verifyaccount\\";
        String i ="verifyglitch1.png";
        icon = new ImageIcon(d+i2+i);
        btnVerify.setIcon(icon);
    }//GEN-LAST:event_btnVerifyMouseReleased

    private void forgotpassbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpassbuttonMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_forgotpassbuttonMouseClicked

    private void btnVerifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="verifyaccount\\";
        String i ="verifyglitch.gif";
        icon = new ImageIcon(d+i2+i);
        btnVerify.setIcon(icon);
       
    }//GEN-LAST:event_btnVerifyMouseEntered

    private void btnVerifyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="verifyaccount\\";
        String i ="verifyclicked1.png";
        icon = new ImageIcon(d+i2+i);
        btnVerify.setIcon(icon);
    }//GEN-LAST:event_btnVerifyMousePressed

    private void btnVerifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="verifyaccount\\";
        String i ="verifyglitch1.png";
        icon = new ImageIcon(d+i2+i);
        btnVerify.setIcon(icon);
    }//GEN-LAST:event_btnVerifyMouseExited

    private void forgotpassbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpassbuttonMousePressed
        // TODO add your handling code here:
        
        ImageIcon icon;
        String i2 ="Forgotpassword\\";
        String i ="forgotpasswordclicked.png";
        icon = new ImageIcon(d+i2+i);
        forgotpassbutton.setIcon(icon);
    }//GEN-LAST:event_forgotpassbuttonMousePressed

    private void forgotpassbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpassbuttonMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Editfilms\\";
        String i ="EDITFILMSanimated.gif";
        icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\images\\Forgot password.png");
        forgotpassbutton.setIcon(icon);
    }//GEN-LAST:event_forgotpassbuttonMouseReleased

    private void signupbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupbuttonMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Signup\\";
        String i ="signupglitch.gif";
        icon = new ImageIcon(d+i2+i);
        signupbutton.setIcon(icon);
    }//GEN-LAST:event_signupbuttonMouseEntered

    private void signupbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupbuttonMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Signup\\";
        String i ="signupclicked.png";
        icon = new ImageIcon(d+i2+i);
        signupbutton.setIcon(icon);
    }//GEN-LAST:event_signupbuttonMousePressed

    private void signupbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupbuttonMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Editfilms\\";
        String i ="EDITFILMSanimated.gif";
        icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\images\\Signup.png");
        signupbutton.setIcon(icon);
    }//GEN-LAST:event_signupbuttonMouseExited

    private void signupbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupbuttonMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Editfilms\\";
        String i ="EDITFILMSanimated.gif";
        icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\images\\Signup.png");
        signupbutton.setIcon(icon);
    }//GEN-LAST:event_signupbuttonMouseReleased

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerify;
    private javax.swing.JButton forgotpassbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JButton signupbutton;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
