/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dvd.management.system;

import DataAccessObject.Billdao;
import DataAccessObject.Filmdao;
import DataAccessObject.Userdao;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.DefaultTableModel;
import model.Bill;
import model.Film;
import model.User;

/**
 *
 * @author ASUS-NOTEBOOK
 */
public class ReturnFilm extends javax.swing.JFrame {
    public String d = "C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\icon\\";
    String dbToken = null;
    String SaveEmail;
    String SaveName;
    int dbid;
    int billid;
    
    /**
     * Creates new form ReturnFilm
     */
    public ReturnFilm() {
        
        initComponents();
        
    }
    public ReturnFilm(int id) {
        initComponents();
        
        jTable1.getTableHeader().setFont(new Font("Retro Gaming", Font.BOLD, 12));
        jTable1.getTableHeader().setForeground(new Color(0,0,0));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.setShowGrid(false);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setBackground(new Color(0,0,0));
        jTable1.setOpaque(false);
        jScrollPane1.getColumnHeader().setVisible(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBackground(Color.BLACK);
        jScrollPane1.getVerticalScrollBar().setBackground(Color.BLACK);
        jScrollPane1.getVerticalScrollBar().setUI(new BasicScrollBarUI(){
             @Override
             protected void configureScrollBarColors() {
                 
                 
            this.thumbColor = Color.cyan;
            }
             
            @Override
             protected JButton createDecreaseButton(int orientation) {
                return createZeroButton();
            }
            @Override    
            protected JButton createIncreaseButton(int orientation) {
                return createZeroButton();
            }
            private JButton createZeroButton() {
            JButton jbutton = new JButton();
            jbutton.setPreferredSize(new Dimension(0, 0));
            jbutton.setMinimumSize(new Dimension(0, 0));
            jbutton.setMaximumSize(new Dimension(0, 0));
            return jbutton;
        }

        });
        
        
        
        txtCost.setBackground(new java.awt.Color(0,0,1));
        txtOtp.setBackground(new java.awt.Color(0,0,1));
        txtTodaydate.setBackground(new java.awt.Color(0,0,1));
        txtduedate.setBackground(new java.awt.Color(0,0,1));
       
        dbid = id;
        User user = null;
        user = Userdao.getAll(id);
        SaveEmail = user.getEmail();
        SaveName = user.getName();
        btnReturn.setEnabled(false);
        

    }
    
    public void tableDetails(){
        Bill bill = new Bill();
        
        String returncode = txtOtp.getText();
        bill = Billdao.getToken(dbid, returncode);
        dbToken = bill.getReturnCode();
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Bill> list = Billdao.getAllRecordsByReturnCode(returncode);
        Iterator<Bill> itr = list.iterator();
        while(itr.hasNext()){
            Bill filmObj = itr.next();
            dtm.addRow(new Object[]{filmObj.getId(),filmObj.getGenre(),filmObj.getTitle(),filmObj.getRentdate(),filmObj.getTotal()});
           
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtOtp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnReturn = new javax.swing.JButton();
        btnApply = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtTodaydate = new javax.swing.JTextField();
        txtduedate = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        border = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOtp.setFont(new java.awt.Font("Retro Gaming", 0, 18)); // NOI18N
        txtOtp.setForeground(new java.awt.Color(255, 255, 255));
        txtOtp.setBorder(null);
        txtOtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOtpKeyReleased(evt);
            }
        });
        jPanel1.add(txtOtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 170, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Genre", "Title", "rentdate", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(137, 92, 183));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(137, 92, 183));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 500, 40));

        btnReturn.setBackground(new java.awt.Color(0, 0, 0));
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgReturnfilm/Return.png"))); // NOI18N
        btnReturn.setBorder(null);
        btnReturn.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Return/returnnotactive.png"))); // NOI18N
        btnReturn.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Return/returnnotactive.png"))); // NOI18N
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReturnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReturnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnReturnMouseReleased(evt);
            }
        });
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        btnApply.setBackground(new java.awt.Color(0, 0, 0));
        btnApply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgforogt/search.png"))); // NOI18N
        btnApply.setBorder(null);
        btnApply.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search/searchinactive.png"))); // NOI18N
        btnApply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnApplyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnApplyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnApplyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnApplyMouseReleased(evt);
            }
        });
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });
        jPanel1.add(btnApply, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgReturnfilm/back.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBackMouseReleased(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        txtTodaydate.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        txtTodaydate.setForeground(new java.awt.Color(255, 255, 255));
        txtTodaydate.setBorder(null);
        jPanel1.add(txtTodaydate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 160, -1));

        txtduedate.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        txtduedate.setForeground(new java.awt.Color(255, 255, 255));
        txtduedate.setBorder(null);
        jPanel1.add(txtduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 160, -1));

        txtCost.setFont(new java.awt.Font("Retro Gaming", 3, 18)); // NOI18N
        txtCost.setForeground(new java.awt.Color(255, 255, 255));
        txtCost.setBorder(null);
        jPanel1.add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 160, -1));

        border.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        border.setForeground(new java.awt.Color(255, 255, 255));
        border.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgReturnfilm/RETURN_FILM_1.png"))); // NOI18N
        jPanel1.add(border, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        String token = txtOtp.getText();
        if(token.equals(dbToken)){
        Date todaydate = new Date();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd MMM yyyy");
        String date = dFormat.format(todaydate);
        Bill bill = null;
        bill = Billdao.getToken(dbid, token);
        
        
       
            
            Billdao.update(token, date);
            setVisible(false);
            
            
            int filmid = bill.getFilmid();
            
            Film film = null;
            film = Filmdao.getFilmByTitletofalse(filmid);
            
            Filmdao.updaterentstatustofalse(film.getId());
           
            Home ep;
            ep = new Home(dbid);
            ep.setVisible(true);
               
        }
        else{
            JOptionPane.showMessageDialog(null,"<html><b style =\"color:red\">DVD Succesfully returned</b></html>","Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        String returncode = txtOtp.getText();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Bill> list = Billdao.getAllRecordsByReturnCode(returncode);
        Iterator<Bill> itr = list.iterator();
        while(itr.hasNext()){
            Bill filmObj = itr.next();
            dtm.addRow(new Object[]{filmObj.getId(),filmObj.getGenre(),filmObj.getTitle(),filmObj.getRentdate(),filmObj.getTotal()});
            
        }
     
    }//GEN-LAST:event_formComponentShown

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        // TODO add your handling code here:
  
        Bill bill = new Bill();
        bill = Billdao.getToken(dbid, txtOtp.getText());
        
        if(bill == null){
            JOptionPane.showMessageDialog(null,"<html><b style =\"color:red\">Return Code does not exist</b></html>","Message", JOptionPane.ERROR_MESSAGE);
        }else{
          
        
        
  
           
            
            String returncode = txtOtp.getText();
            dbToken = bill.getReturnCode();
            Boolean returnfilm = false;
            Boolean dbType = bill.getReturnFilm();
            
            if(returncode.equals(dbToken)&& returnfilm.equals(dbType)){
                btnApply.setEnabled(false);
                btnReturn.setEnabled(true);
                JOptionPane.showMessageDialog(null,"Return Code Exist","Message", JOptionPane.INFORMATION_MESSAGE);
                Date todaydate = new Date();
                SimpleDateFormat dFormat = new SimpleDateFormat("dd MMM yyyy");
                String date = dFormat.format(todaydate);
                txtTodaydate.setText(date);
                txtduedate.setText(bill.getDuedate());
                int cost = bill.getCost();   
                
                
                if (date.compareTo(bill.getDuedate())>0) {
                    JOptionPane.showMessageDialog(null,"Rent overdue P200 added to total cost","Message", JOptionPane.ERROR_MESSAGE);
                    int addcost = 200;
                    cost += addcost; 
                    Billdao.updateCost(dbToken, cost);
                    //bill.setCost(cost);
              
                } 
                String s = String.valueOf(cost);
                txtCost.setText(s);
                
                tableDetails();
            }
            else if(returncode.equals(dbToken)&& dbType.equals(true)){
                JOptionPane.showMessageDialog(null,"Return Code Already Used","Message", JOptionPane.ERROR_MESSAGE);
            }
        }
              
        
    }//GEN-LAST:event_btnApplyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            Home ep;
            ep = new Home(dbid);
            ep.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtOtpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOtpKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtOtpKeyReleased

    private void btnApplyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplyMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Search\\";
        String i ="searchhover.png";
        icon = new ImageIcon(d+i2+i);
        btnApply.setIcon(icon);
        
    }//GEN-LAST:event_btnApplyMouseEntered

    private void btnApplyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplyMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Search\\";
        String i ="C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\imgver\\search.png";
        icon = new ImageIcon(i);
        btnApply.setIcon(icon);
    }//GEN-LAST:event_btnApplyMouseExited

    private void btnApplyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplyMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Search\\";
        String i ="searchclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnApply.setIcon(icon);
    }//GEN-LAST:event_btnApplyMousePressed

    private void btnApplyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplyMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Search\\";
        String i ="C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\imgver\\search.png";
        icon = new ImageIcon(i);
        btnApply.setIcon(icon);
    }//GEN-LAST:event_btnApplyMouseReleased

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="back\\";
        String i ="backhover.png";
        icon = new ImageIcon(d+i2+i);
        btnBack.setIcon(icon);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="back\\";
        String i ="back.png";
        icon = new ImageIcon(d+i2+i);
        btnBack.setIcon(icon);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="back\\";
        String i ="backclick.png";
        icon = new ImageIcon(d+i2+i);
        btnBack.setIcon(icon);
    }//GEN-LAST:event_btnBackMousePressed

    private void btnBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="back\\";
        String i ="back.png";
        icon = new ImageIcon(d+i2+i);
        btnBack.setIcon(icon);
    }//GEN-LAST:event_btnBackMouseReleased

    private void btnReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Return\\";
        String i ="returnhover.png";
        icon = new ImageIcon(d+i2+i);
        btnReturn.setIcon(icon);
        
        
    }//GEN-LAST:event_btnReturnMouseEntered

    private void btnReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnReturnMouseClicked

    private void btnReturnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMousePressed
        // TODO add your handling code here:
         ImageIcon icon;
        String i2 ="Return\\";
        String i ="returnnclick.png";
        icon = new ImageIcon(d+i2+i);
        btnReturn.setIcon(icon);
    }//GEN-LAST:event_btnReturnMousePressed

    private void btnReturnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseReleased
        // TODO add your handling code here:
         ImageIcon icon;
        //String i2 ="Return\\";
        //String i ="renturnn.png";
        icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\imgReturnfilm\\return.png");
        btnReturn.setIcon(icon);
    }//GEN-LAST:event_btnReturnMouseReleased

    private void btnReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseExited
        // TODO add your handling code here:
         ImageIcon icon;
        //String i2 ="Return\\";
        //String i ="renturnn.png";
        icon = new ImageIcon("C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\imgReturnfilm\\return.png");
        btnReturn.setIcon(icon);
    }//GEN-LAST:event_btnReturnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel border;
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReturn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtOtp;
    private javax.swing.JTextField txtTodaydate;
    private javax.swing.JTextField txtduedate;
    // End of variables declaration//GEN-END:variables
}
