/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dvd.management.system;

import javax.swing.JOptionPane;
import model.User;
import DataAccessObject.Userdao;
import DataAccessObject.otp;
import javax.swing.ImageIcon;

public class verifyaccount extends javax.swing.JFrame {
    
    private String dbToken = null;
    private String email = null;
    public String emailPattern = "^(.+)@(.+)$";
    public String d = "C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\icon\\";
    

    /**
     * Creates new form verifyaccount
     */
    public verifyaccount() {
        initComponents();
        txtEmail.setBackground(new java.awt.Color(0,0,1));
        txtToken.setBackground(new java.awt.Color(0,0,1));
        
        this.setLocationRelativeTo(null);
        btnSearch.setEnabled(false);
        btnverify.setEnabled(false);
        txtToken.setEditable(false);
    }
         
    public void clear(){
        
        btnSearch.setEnabled(false);
        txtEmail.setEditable(true);
        txtEmail.setText("");
        txtToken.setText("");
        
    }
    
    public void validateEmail(){
        email = txtEmail.getText();
        if(email.matches(emailPattern)){
            btnSearch.setEnabled(true);
        }
        else{
            btnSearch.setEnabled(false);
        }
    }
    
    public void validateFields (){
        String token = txtToken.getText();
        
        if(!token.equals("")){
            btnverify.setEnabled(true);
        }
        else {
            btnverify.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtToken = new javax.swing.JTextField();
        btnverify = new javax.swing.JToggleButton();
        btnSearch = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 160, -1));

        txtToken.setFont(new java.awt.Font("Retro Gaming", 0, 12)); // NOI18N
        txtToken.setForeground(new java.awt.Color(255, 255, 255));
        txtToken.setBorder(null);
        txtToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTokenActionPerformed(evt);
            }
        });
        txtToken.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTokenKeyReleased(evt);
            }
        });
        jPanel1.add(txtToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 150, -1));

        btnverify.setBackground(new java.awt.Color(0, 0, 0));
        btnverify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgver/save.png"))); // NOI18N
        btnverify.setBorder(null);
        btnverify.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save/saveinactive.png"))); // NOI18N
        btnverify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnverifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnverifyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnverifyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnverifyMouseReleased(evt);
            }
        });
        btnverify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifyActionPerformed(evt);
            }
        });
        jPanel1.add(btnverify, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 50, -1));

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgver/search.png"))); // NOI18N
        btnSearch.setBorder(null);
        btnSearch.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search/searchinactive.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSearchMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSearchMouseReleased(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 50, -1));

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgver/Exit.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 10, 10));

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgver/verfiedlogin.png"))); // NOI18N
        btnLogin.setBorder(null);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoginMouseReleased(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgver/Verify.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 332));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        validateEmail();
  
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtTokenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTokenKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtTokenKeyReleased

    private void btnverifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifyActionPerformed
        // TODO add your handling code here:
       
       otp o = new otp();
       int l = 6; //max lenght of otp
       String newToken = String.valueOf(o.method(l));
       String email = txtEmail.getText();
        
       String token = txtToken.getText();
       
   
        if(token.equals(dbToken)){
            Userdao.updateToken(email, newToken);
            Userdao.updateStatus(email);
            clear();
            setVisible(false);
            new Loginback().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"<html><b style =\"color:red\">Incorrect OTP</b></html>","Message", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnverifyActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        email = txtEmail.getText();
        
        
        User user = null;  
        user = Userdao.getToken(email);
        
        
        if(user == null){
                JOptionPane.showMessageDialog(null,"<html><b style =\"color:red\">Incorrect E-mail</b></html>","Message", JOptionPane.ERROR_MESSAGE);
            }
            else {
                    User status = null;
                    status = Userdao.getStatus(email);
                    if (status.getStatus().equals("Disabled")){
                        btnSearch.setEnabled(false);
                        txtEmail.setEditable(false);
                        txtToken.setEditable(true);
                        btnverify.setEnabled(true);
                        dbToken = user.getToken();
                        txtEmail.setText(user.getEmail());
                        validateFields();
                    }
                else {
                    JOptionPane.showMessageDialog(null,"<html><b style =\"color:red\">Account is Already Verified</b></html>","Message", JOptionPane.ERROR_MESSAGE);
                }


            }
        
       
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTokenActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to close the Application?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        setVisible(false);
       new Loginback().setVisible(true);
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Verifiedlogin\\";
        String i ="verfiedloginhover.png";
        icon = new ImageIcon(d+i2+i);
        btnLogin.setIcon(icon);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Verifiedlogin\\";
        String i ="verfiedlogin.png";
        icon = new ImageIcon(d+i2+i);
        btnLogin.setIcon(icon);
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Verifiedlogin\\";
        String i ="verfiedloginhover.png";
        icon = new ImageIcon(d+i2+i);
        btnLogin.setIcon(icon);
    }//GEN-LAST:event_btnLoginMouseReleased

    private void btnLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Verifiedlogin\\";
        String i ="verfiedloginclick.png";
        icon = new ImageIcon(d+i2+i);
        btnLogin.setIcon(icon);
    }//GEN-LAST:event_btnLoginMousePressed

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Search\\";
        String i ="searchhover.png";
        icon = new ImageIcon(d+i2+i);
        btnSearch.setIcon(icon);
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Search\\";
        String i ="C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\imgver\\search.png";
        icon = new ImageIcon(i);
        btnSearch.setIcon(icon);
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Search\\";
        String i ="C:\\Users\\ASUS-NOTEBOOK\\Documents\\NetBeansProjects\\DVD Management System\\src\\imgver\\search.png";
        icon = new ImageIcon(i);
        btnSearch.setIcon(icon);
    }//GEN-LAST:event_btnSearchMouseReleased

    private void btnSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Search\\";
        String i ="searchclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnSearch.setIcon(icon);
    }//GEN-LAST:event_btnSearchMousePressed

    private void btnverifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnverifyMouseEntered
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Save\\";
        String i ="savehover.png";
        icon = new ImageIcon(d+i2+i);
        btnverify.setIcon(icon);
    }//GEN-LAST:event_btnverifyMouseEntered

    private void btnverifyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnverifyMousePressed
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Save\\";
        String i ="saveclicked.png";
        icon = new ImageIcon(d+i2+i);
        btnverify.setIcon(icon);
    }//GEN-LAST:event_btnverifyMousePressed

    private void btnverifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnverifyMouseExited
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Save\\";
        String i ="save.png";
        icon = new ImageIcon(d+i2+i);
        btnverify.setIcon(icon);
        
    }//GEN-LAST:event_btnverifyMouseExited

    private void btnverifyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnverifyMouseReleased
        // TODO add your handling code here:
        ImageIcon icon;
        String i2 ="Save\\";
        String i ="save.png";
        icon = new ImageIcon(d+i2+i);
        btnverify.setIcon(icon);
    }//GEN-LAST:event_btnverifyMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verifyaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verifyaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verifyaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verifyaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verifyaccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSearch;
    private javax.swing.JToggleButton btnverify;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtToken;
    // End of variables declaration//GEN-END:variables
}
